#!/bin/bash
set -ex
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.secrets/gcp/backups-sa-key.json
restic --repo gs:marksteve:/secrets.enc backup $HOME/Sync/.secrets.enc
# restic --repo s3:https://s3.amazonaws.com/marksteve/secrets.enc backup $HOME/Sync/.secrets.enc
